name: Notify Forks

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to fork
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: Ruben0304/PlayUpFrontend
          event-type: push_event
          client-payload: '{"ref": "${{ github.ref }}"}'
