name: Sync on Upstream Push

on:
  repository_dispatch:
    types: [push_event]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: github.event.client_payload.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: master
          
      - name: Configurar Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Sincronizar con upstream
        run: |
          git remote add upstream https://github.com/PlayUpOrg/PlayUpFrontend.git
          git fetch upstream master
          
          # Crear una rama temporal para la fusión
          git checkout -b temp-merge-branch
          
          # Fusionar excluyendo archivos de workflow
          git merge -X ours --no-commit upstream/master
          git reset HEAD .github/workflows/
          git checkout -- .github/workflows/
          
          # Confirmar y enviar los cambios
          git commit -m "Merge upstream changes excluding workflows"
          git checkout master
          git merge temp-merge-branch
          git push origin master
